### ISSUE TITLE
Make compatible with latest version of infisical paths

### ISSUE THREAD

**Issue by cameronclaero** [scareyo/ansible-collection-infisical#1]
Hi there, wondering if you could add the extra parameter that is available now in the infisical sdk for the folder paths:

ie secret = client.get_secret("API_KEY", environment="dev", path="/")

Thanks

**Comment by scareyo** [comment]
I added options for both env and path in [23f2527](https://github.com/scareyo/ansible-collection-infisical/commit/23f25275d3c1a21e44a0033f926622b23f4cca9a). For example:
```
- name: Print secret specifying an environment and path
  debug: msg="{{ lookup('scareyo.infisical.infisical', 'TEST_FOLDER_VALUE', env='staging', path='/folder') }}"
```

**Comment by cameronclaero** [comment]
@scareyo  Awesome thanks for that, any chance to publish to ansible-galaxy?

**Comment by scareyo** [comment]
I'm having trouble accessing my ansible galaxy namespace. Seems some others are also facing the same issue since the new ansible galaxy service was released (https://forum.ansible.com/t/namespace-changed-and-collection-upload-not-working/1314).

Once that's resolved I'll push the release.

**Comment by cameronclaero** [comment]
Could you update galaxy.yml version number as well? Trying to install directly instead

**Comment by scareyo** [comment]
I updated the version in git. I have access to my namespace now, but another Galaxy NG issue prevents me from uploading the collection:

https://access.redhat.com/solutions/7033171
